---

- name: install kafka
  hosts: lab_core_services
  become: yes
  tasks:

  # install Kafka
  - name: install kafka
    ansible.builtin.include_role:
      name: kafka
    vars:    
      action: "install"
