---

- name: Install ClamAV
  hosts: lab_core_services
  become: yes
  tasks:

  # Install ClamAV and Clamd virus scanner
  - name: Install ClamAV Virusscaner
    ansible.builtin.include_role:
      name: clam-av
    vars:    
      action: "install"
