---
- name: Kafka
  hosts: lab_core_services
  become: yes
  tasks:

    # install 
    - name: install kafka
      ansible.builtin.include_role:
        name: kafka
      vars:
        action_type: "install"
