---

#########################################################
## Kafka role defaults                          ##
#########################################################

# default role variables for the kafka role
kafka_pod:
  # address is the URL to connect to the Kafka server.
  address: ""
  # username is the username to connect to the Kafka server.
  username: ""
  # password is the password to connect to the Kafka server.
  password: ""
  # token is the token used to authenticate to the Kafka server.
  token: ""
    
  # metadata contains information about the role.
  metadata:
    name: "kafka"
    description: "Ansible role for Kafka-server and kafka-ui."
    version: "0.0.4"
    maintainer: "Team UCC Automation"
    maintainer_email: "m.venema.04@mindef.nl"
  # KAFKA-SERVER-POD
  pods:
    pod:
    # name is the name of the pod used in podman or docker. example: "vault.pod".
      pod_name: "kafka.pod"
    # network is the name of the network used in the pod. example: "vault_network".
      pod_network: "kafka_network"
    # network_ports is a list of ports used in the container. example: "8200:8200", "8201:8201".
      pod_network_ports: [ "9092:9092", "8090:8080" ]
    # uninstall is a boolean value to indicate if the pod should be uninstalled. Default is false.
      uninstall: false
    # platform is the platform used for the pod. example: "podman", "docker", "kubernetes". Default is "podman".
      platform: "podman"

  # KAFKA-UI-CONTAINER
  containers:
    ui:
      container_name: "kafka_ui"
    # name is the name of the container used in podman or docker. example: "vault".
      container_volumes:
        - "kafka-ui:/etc/kafkaui:Z"
      volume_mode: "0777"
      container_repository_url: "docker.io/provectuslabs/kafka-ui" #"mindef.nl/containers/kafka-ui_0.28.4.tar"
      container_repository_tag: "latest"
    # platform is the platform used for the container. example: "podman", "docker". Default is "podman".
      platform: "podman"
    # uninstall indicates if the container should be uninstalled. Default is false.
      uninstall: false
    # repository_url can be a URL to a docker image or a tar file. example: "https://docker.io/sonatype/nexus3" or "/tmp/nexus3.67.1.tar", "https://192.168.1.1/repo/nexus.tar".
    # repository_url: docker.io/apache/kafka #"mindef.nl/containers/kafka-server_0.0.75.tar"
    # repository_checksum can be a checksum of the container file. example: "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef" or "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef".
    # repository_checksum: "" TODO
    # repository_checksum_algorithm can be a checksum algorithm of the container file. example: "sha256", sha512", "md5".
    # repository_checksum_algorithm: "" TODO
    # repository_tag can be a tag of the image or a version of the tar file. example: "3.67.1" or "latest" Default is "latest".
    # repository_tag: "" TODO
    # environment is a list of environment variables used in the container.

      container_env:
        DYNAMIC_CONFIG_ENABLED: true
        AUTH_TYPE: "LOGIN_FORM"
        SPRING_SECURITY_USER_NAME: admin
        SPRING_SECURITY_PASSWORD: pass

      containter_healthcheck:
      container_quadlet_options:
        - |
          [Unit]
          Description=Kafka UI
          Requires=container_kafka_server.service
          After=container_kafka_server.service
    
    # KAFKA-SERVER-CONTAINER
    server:
      container_name: "kafka_server"
      platform: "podman"
      container_repository_url: "docker.io/apache/kafka"
      container_repository_tag: 4.0.0
      container_volumes:
        - "kafka/data:/var/lib/kafka/data:Z"
      volume_mode: "0777"
      container_env:
        CLUSTER_ID: "KAFKA" # A unique ID for the Kafka cluster
        KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://{{ ansible_default_ipv4.address }}:9092"
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # Kafka will automatically create topics if needed.
        KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" # Defines the controller listener.
        KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093" # Defines the controller voters.
        KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
        KAFKA_NODE_ID: 1 # A unique ID for the Kafka instance.
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Since we're running one broker, one replica is enough.
        KAFKA_PROCESS_ROLES: "broker,controller" # Kafka acts as both broker and controller.
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      container_healthcheck: "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka_server:9092 || exit 1" 
      container_healthcheck_start: "60s"

kafka_server_secret_engine_name: "kafka-pod"
kafka_server_secret_engine_description: "Secrets for Apache Kafka server and Kafka-UI"